# -*- coding: utf-8 -*-
"""challenge-telecom-x-analisis-evasion-clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SN3AqpoJuhjrLRjrSVw1XVQ2o0ftTe2T
"""

import pandas as pd
from pandas import json_normalize
import requests

df = json_normalize(requests.get("https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json").json())

print(f"Shape: {df.shape}")
print(f"\nColumnas:\n{df.columns.tolist()}")
print(f"\nTipos de datos:\n{df.dtypes}")
print(f"\nValores nulos:\n{df.isnull().sum()}")
print(f"\nMuestra de datos:")
display(df.head(2))

"""# **Transformación**

# **Comprobación de incoherencias en los datos**
"""

print("Valores nulos por columna:")
print(df.isnull().sum())
print(f"\nRegistros duplicados: {df.duplicated().sum()}")
print("\nValores únicos en columnas categóricas:")
for col in df.select_dtypes(include='object').columns:
    print(f"{col}: {df[col].dropna().unique()[:10]}")

"""# **Manejo de inconsistencias**"""

df['Cuentas_Diarias'] = pd.to_numeric(df['account.Charges.Monthly'], errors='coerce') / 30.44
print(df[['account.Charges.Monthly', 'Cuentas_Diarias']].head())

"""# **Columna de cuentas diarias**"""

df['Cuentas_Diarias'] = df['acc_charges_Monthly'] / 30.44
df.head()

print(df[['acc_charges_Monthly', 'Cuentas_Diarias']].describe())

df.to_csv('telecomx_con_diarias.csv', index=False)

"""# **Carga y análisis(L - Load & Analysis)**

# Análisis Descriptivo
"""

import pandas as pd
from pandas import json_normalize
import requests

df = json_normalize(requests.get("https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json").json())
df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'].astype(str).str.replace('[^0-9.]', '', regex=True), errors='coerce')

print("ESTADÍSTICAS DESCRIPTIVAS - VARIABLES NUMÉRICAS")
print("="*60)
stats = df.describe().round(2)
stats.index = ['Cantidad', 'Promedio', 'Desv. Estándar', 'Mínimo', '25%', 'Mediana', '75%', 'Máximo'] # Fixed: Changed .columns to .index
print(stats)

print("\nDISTRIBUCIÓN - VARIABLES CATEGÓRICAS PRINCIPALES")
print("="*60)
for col in ['Churn', 'customer.gender', 'customer.Partner', 'account.Contract']:
    print(f"\n{col}:")
    print(df[col].value_counts().to_frame('Conteo').assign(Porcentaje=lambda x: (x/x.sum()*100).round(1).astype(str)+'%'))

"""# **Distribución de evasión**"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('telecomx_limpio.csv')
df['fuga'] = df['Churn'].map({'Yes': 1, 'No': 0})

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
df['fuga'].value_counts().plot.pie(ax=axes[0], labels=['No fuga', 'Fuga'], autopct='%1.1f%%', colors=['#2ecc71', '#e74c3c'], startangle=90)
axes[0].set_ylabel('')
axes[0].set_title('Proporción de fuga')
df['fuga'].value_counts().plot.bar(ax=axes[1], color=['#2ecc71', '#e74c3c'])
axes[1].set_xticks([0, 1])
axes[1].set_xticklabels(['No', 'Sí'])
axes[1].set_title('Conteo de clientes')
plt.tight_layout()
plt.show()

print(f"Clientes con fuga: {(df['fuga']==1).sum():,} ({df['fuga'].mean()*100:.2f}%)")
print(f"Clientes sin fuga: {(df['fuga']==0).sum():,} ({(1-df['fuga'].mean())*100:.2f}%)")

"""# **Recuento de evasión por variables categóricas**"""

import pandas as pd
import matplotlib.pyplot as plt
from pandas import json_normalize
import requests

df = json_normalize(requests.get("https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json").json())
df['Churn_num'] = df['Churn'].map({'Yes': 1, 'No': 0})

cols = ['customer.gender', 'customer.SeniorCitizen', 'customer.Partner', 'account.Contract', 'account.PaperlessBilling']
titles = ['Género', 'Senior', 'Pareja', 'Contrato', 'Factura electrónica']

fig, axes = plt.subplots(2, 3, figsize=(12, 6))
for idx, (col, title) in enumerate(zip(cols, titles)):
    ax = axes[idx//3, idx%3]
    rates = df.groupby(col)['Churn_num'].mean()
    if len(rates) > 0:
        rates.plot.bar(ax=ax, color=['#3498db', '#e74c3c', '#9b59b6'][:len(rates)])
        ax.set_title(f'Fuga - {title}')
        ax.set_ylabel('Tasa')
plt.tight_layout()
plt.show()

for col, title in zip(cols, titles):
    print(f"\n{title}:")
    print(df.groupby(col)['Churn_num'].agg(['mean', 'count']).round(3))

"""# **Conteo de evasión por variables numéricas**"""

import pandas as pd
import matplotlib.pyplot as plt
from pandas import json_normalize
import requests

df = json_normalize(requests.get("https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json").json())
df['Churn_num'] = df['Churn'].map({'Yes': 1, 'No': 0})
df['customer.tenure'] = pd.to_numeric(df['customer.tenure'], errors='coerce')
df['account.Charges.Monthly'] = pd.to_numeric(df['account.Charges.Monthly'], errors='coerce')
df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'].astype(str).str.replace('[^0-9.]', '', regex=True), errors='coerce')

num_cols = ['customer.tenure', 'account.Charges.Monthly', 'account.Charges.Total']
titles = ['Antigüedad (meses)', 'Cargo mensual', 'Cargo total']

fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for idx, (col, title) in enumerate(zip(num_cols, titles)):
    ax = axes[idx]
    df[df['Churn_num']==0][col].dropna().plot(kind='hist', bins=30, ax=ax, alpha=0.5, label='No fuga', color='#2ecc71', edgecolor='black')
    df[df['Churn_num']==1][col].dropna().plot(kind='hist', bins=30, ax=ax, alpha=0.5, label='Fuga', color='#e74c3c', edgecolor='black')
    ax.set_title(f'{title}')
    ax.set_xlabel('')
    ax.legend(fontsize=8)
plt.tight_layout()
plt.show()

print("Estadísticas por grupo de fuga:\n")
for col, title in zip(num_cols, titles):
    print(f"\n{title}:")
    print(df.groupby('Churn_num')[col].agg(['mean', 'median', 'std', 'count']).round(2))

"""# **Informe final**

1. INTRODUCCIÓN
Este análisis identifica los factores que influyen en la evasión de clientes de TelecomX. La empresa presenta una tasa de churn del 26.5%, equivalente a 1,869 clientes perdidos de un total de 7,043. El objetivo es proporcionar insights accionables para mejorar la retención.
2. LIMPIEZA DE DATOS
Se cargaron los datos desde la API en formato JSON, se eliminaron 224 registros con valores vacíos en la variable Churn, se convirtió el cargo total a formato numérico y se validó la consistencia del dataset final de 7,043 registros.
3. HALLAZGOS PRINCIPALES
Factores con mayor impacto en la fuga:
Tipo de contrato: Los clientes con contratos mensuales tienen 42.7% de fuga, versus 2.8% en contratos de dos años. Este es el predictor más fuerte.
Antigüedad: Los clientes que se van promedian 18 meses con la empresa, frente a 37.6 meses de quienes permanecen. Los primeros 12 meses son críticos.
Adultos mayores: Presentan 41.7% de fuga, casi el doble que el resto de la base (23.6%).
Cargo mensual: Los clientes que pagan más tienen mayor probabilidad de fuga ($74.44 vs $61.27), sugiriendo posibles problemas de percepción de valor.
Facturación electrónica: Asociada con el doble de tasa de fuga (33.6% vs 16.3%).
Variables sin impacto significativo:
Género: Tasa de fuga similar entre hombres (26.2%) y mujeres (26.9%).
4. CONCLUSIONES
El compromiso de largo plazo mediante contratos es el factor más determinante para la retención. Los clientes nuevos y los adultos mayores representan segmentos de alto riesgo. La relación precio-retención no es lineal, lo que indica oportunidades para ajustar la propuesta de valor en planes premium.
5. RECOMENDACIONES
Incentivar la migración de contratos mensuales a anuales con descuentos del 10-15%.
Implementar un programa de onboarding reforzado para los primeros 90 días de relación con el cliente.
Diseñar atención diferenciada para adultos mayores, con soporte prioritario y comunicación adaptada.
Revisar la estructura de precios de planes superiores a $80 mensuales para mejorar la percepción de valor.
Establecer métricas de seguimiento: reducir churn al 18% en seis meses y lograr 25% de conversión de contratos mensuales a anuales.
La implementación priorizada de estas recomendaciones tiene el potencial de reducir significativamente la evasión y mejorar la sostenibilidad del negocio.
"""